### ISSUE TITLE
remote_write filter

### ISSUE THREAD

**Issue by garg-kapil** [Telefonica/prometheus-kafka-adapter#105]
Hi,

I want to apply filter on remote write
like this
```

- url: "http://172.17.10.183:8080/receive"
   writeRelabelConfigs:
  - sourceLabels: [__name__]
    regex: node_cpu_hourly_cost
    action: keep
  - sourceLabels: [__name__]
    regex: node_gpu_hourly_cost
    action: keep
  - sourceLabels: [__name__]
    regex: node_ram_hourly_cost
    action: keep  
```

but it is not working I am using promethus deployed using prometheus operator 
neither i can see any logs etc on promethus or in  prometheus-kafka-adapter pods logs
Can anyone help..??
