### ISSUE TITLE
Filter metrics based on key words

### ISSUE THREAD

**Issue by ingared8** [Telefonica/prometheus-kafka-adapter#19]
Instead of accepting all metrics, provide a mechanism to filter messages (belonging to specific applications with keywords /regex).

**Comment by palmerabollo** [comment]
Thanks for your feedback. We are thinking about it because we're not sure about whether the adapter is the best place to do the filtering.

An alternative would be to have a secondary/federated prometheus instance scraping metrics from the main one and sending it to your prometheus-kafka-adapter. In its config you can filter what metrics you need to gather:

```
global:
  scrape_interval: 60s

remote_write:
  - url: http://your-prometheus-kafka-adapter:8080/receive

scrape_configs:
  - job_name: 'federate'

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - container_cpu_usage_seconds_total{id="/"}
        - container_memory_usage_bytes{id="/"}

    static_configs:
      - targets:
          - main-prometheus:8080
```

You can find more info about prometheus federation at https://github.com/prometheus/prometheus/blob/master/docs/federation.md.
