### ISSUE TITLE
Supporting customisation when publishing to Kafka

### ISSUE THREAD

**Issue by vnydvd** [Telefonica/prometheus-kafka-adapter#51]
I have a question where I want community's suggestion and guidance.

A live prometheus server will be getting too many metrics per second and if say we want to selectively publish them to Kafka (considering Kafka being used by too many sibling applications in the flow) do you think adding a check in this Adapter is right strategy or it can/should be controlled at prometheus (while doing remote_write)?

**Comment by palmerabollo** [comment]
Hi, Vinay @vnydvd. Welcome to this repo.

That's a very good question. Filtering time series as close to the source as possible (prometheus) looks more efficient to me, to avoid sending data you want to discard. So we have a [federated prometheus](https://prometheus.io/docs/prometheus/latest/federation/#configuring-federation) that scrapes a subset of time series from the main Prometheus server. We select those we are interested in using `match[]`. This is how the config looks like:

```yaml
global:
  scrape_configs:
    - job_name: 'federate'
      scrape_interval: 30s

      honor_labels: true
      metrics_path: '/federate'

      params:
        'match[]':
          - container_memory_working_set_bytes{id="/"}
          - '{__name__=~"probe_.*"}'

      static_configs:
        - targets:
          - prometheus:9090  # main prometheus server

  remote_write:
    - url: http://prometheus-kafka-adapter:8080/receive
```

I'm not saying this is the best approach or what I recommend in all scenarios. It's only one approach that is working for us (so far 🤞). I've asked myself the same question many times, I'm also interested in what other people think about it.
