### ISSUE TITLE
update README. add step for setting prometheus

### ISSUE THREAD

**Issue by DS-Tikhonov** [Telefonica/prometheus-kafka-adapter#6]
Hello @javierprovecho , add step for config prometheus.yml:
```
remote_write:
  - url: "http://prometheus_kafka_adapter:8080/receive"


```

just about it never said.

And simple compose file docker-compose.yml:
```
  kafka_adapter:
    image: prometheus-kafka-adapter
    container_name: prometheus_kafka_adapter
    networks:
      - monitor_net
    environment:
      - LOG_LEVEL=error
      - KAFKA_BROKER_LIST=ip:port
      - KAFKA_TOPIC=prometheus-metrics
      - PORT=8080
    expose:
      - 8080

```
